let GLOBAL_DATA = {
  PAGE_NUMBER: 0,
  SELECT_RANGE_TEXT: '',
  SELECT_RANGE_TEXT_PREV: '',
  SELECT_RANGE_TEXT_NEXT: '',
  SELECT_START: 0,
  SELECT_END: 0,
  SELECT_IMAGE: '',
  MOUSE_CLICK_ID: '',

};
export default GLOBAL_DATA;
